name: '${project.name}'
version: '${project.version}'
main: me.d2siado.dev.Lootbox
authors: [ D2SI4DO ]
description: A special plugin of lootbox like AstralMC
commands:
  lootbox:
    aliases:
      - lootbox
      - box
    description: The principal command of the plugin
